FROM apache/airflow:3.0.2

USER root
RUN apt-get update && \
    apt-get install -y docker.io docker-compose-plugin && \
    apt-get clean
USER airflow

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt