FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY download_data.py .

RUN mkdir -p /root/.kaggle
RUN mkdir -p /data

CMD ["python", "download_data.py"]